apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: prod-
namespace: production
labels:
  - pairs:
      app.kubernetes.io/part-of: myapp
    includeSelectors: true
commonAnnotations:
  managed-by: syngit
resources:
  - ../../base
patches:
  - path: deployment.yaml
