package kustomizeprovider

import (
	"fmt"
	"io/fs"
	"path"
	"reflect"
	"strings"

	admissionv1 "k8s.io/api/admission/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	"sigs.k8s.io/yaml"
)

// Objects without the bundle label are not managed by this provider.
func IsHandled(obj *unstructured.Unstructured) bool {
	_, ok := obj.GetLabels()[BundleLabel]
	return ok
}

// obj is the old object on DELETE. Without resourceFinder, every object that
// changes git must carry PathAnnotation.
func Resolve(obj *unstructured.Unstructured, op admissionv1.Operation, repo fs.FS, resourceFinder bool) (Decision, error) {
	d := Decision{
		BundleRoot: obj.GetAnnotations()[RootAnnotation],
		Overlay:    obj.GetLabels()[OverlayLabel],
		Owner:      OwnerNone,
	}
	if d.Overlay == "" {
		return refuse(d, "%s has the %s label but no %s label", obj.GetName(), BundleLabel, OverlayLabel)
	}
	if d.BundleRoot == "" {
		return refuse(d, "%s has no %s annotation", obj.GetName(), RootAnnotation)
	}

	b, err := buildOverlay(repo, d.BundleRoot, d.Overlay)
	if err != nil {
		return d, err
	}
	full, err := b.index(b.full)
	if err != nil {
		return d, err
	}
	built, found := full.match(obj)
	if found {
		d.Owner = built.Owner
		d.OriginalName = built.OriginalName
	}

	r := resolver{build: b, obj: obj, built: built, resourceFinder: resourceFinder}
	switch op {
	case admissionv1.Delete:
		return r.resolveDelete(d)
	case admissionv1.Create, admissionv1.Update:
		return r.resolveApply(d, found, generatorNames(full))
	}
	return d, fmt.Errorf("unsupported operation %s", op)
}

type resolver struct {
	build          overlayBuild
	obj            *unstructured.Unstructured
	built          builtResource
	resourceFinder bool
}

func (r resolver) resolveDelete(d Decision) (Decision, error) {
	switch d.Owner {
	case OwnerOverlay:
		d.Action = ActionDeleteResource
		return r.withTargetPath(d, r.built.OriginPath)
	case OwnerNone:
		d.Action = ActionNoOp
		return d, nil
	}
	if r.obj.GetAnnotations()[AllowDeleteAnnotation] == "true" {
		d.Action = ActionNoOp
		return d, nil
	}
	return refuse(d, "%s comes from the %s and cannot be deleted without the %s: \"true\" annotation",
		r.obj.GetName(), d.Owner, AllowDeleteAnnotation)
}

func (r resolver) resolveApply(d Decision, found bool, generatorNames map[string]string) (Decision, error) {
	if found {
		live, built := normalizePair(r.obj, r.built.Object, generatorNames)
		if reflect.DeepEqual(live.Object, built.Object) {
			d.Action = ActionNoOp
			return d, nil
		}
		switch d.Owner {
		case OwnerBase, OwnerComponent:
			return r.resolvePatch(d, generatorNames)
		case OwnerOverlay:
			return r.writeResource(d, live, r.built.OriginPath)
		case OwnerGenerator:
			return refuse(d, generatedRefusal, r.obj.GetName())
		}
	}

	// From here, the object is absent from the git build, or built from outside the bundle.
	annotations := r.obj.GetAnnotations()
	if annotations[GeneratedAnnotation] == "true" {
		return refuse(d, generatedRefusal, r.obj.GetName())
	}
	if annotations[OverlayOnlyAnnotation] != "true" {
		return refuse(d, "%s has no counterpart in the git build of overlay %s; set %s: \"true\" if it is a new overlay resource",
			r.obj.GetName(), d.Overlay, OverlayOnlyAnnotation)
	}

	prefix, suffix, err := r.build.nameAffixes()
	if err != nil {
		return d, err
	}
	d.OriginalName = strings.TrimSuffix(strings.TrimPrefix(r.obj.GetName(), prefix), suffix)
	live := normalize(r.obj, generatorNames)
	// The namespace comes from the overlay or from `kubectl apply -n`.
	live.SetNamespace("")
	return r.writeResource(d, live, r.defaultPath(d.OriginalName, ".yaml"))
}

const generatedRefusal = "%s is generated by a configMapGenerator or secretGenerator, which must be changed in git"

func (r resolver) resolvePatch(d Decision, generatorNames map[string]string) (Decision, error) {
	baseline, err := r.build.index(r.build.baseline)
	if err != nil {
		return d, err
	}
	baselineResource, ok := baseline.match(r.obj)
	if !ok {
		return d, fmt.Errorf("%s is in the build of overlay %s but not in its baseline", r.obj.GetName(), d.Overlay)
	}

	live, base := normalizePair(r.obj, baselineResource.Object, generatorNames)
	operations, err := json6902Patch(live, base)
	if err != nil {
		return d, err
	}
	d.PatchStrategy, err = patchStrategy(r.obj, operations)
	if err != nil {
		return refuse(d, "%s", err)
	}

	d.Action = ActionPatch
	if d.PatchStrategy == PatchStrategyJSON6902 {
		d.JSON6902Patch = operations
	} else {
		d.StrategicMergePatch, err = strategicMergePatch(live, base, d.OriginalName)
		if err != nil {
			return d, err
		}
	}

	patchPath, err := r.findPatchPath(d.OriginalName)
	if err != nil {
		return d, err
	}
	return r.withTargetPath(d, patchPath)
}

func (r resolver) writeResource(d Decision, live *unstructured.Unstructured, autoPath string) (Decision, error) {
	live.SetName(d.OriginalName)
	d.Action = ActionWriteResource
	d.Resource = live
	return r.withTargetPath(d, autoPath)
}

// The target path must stay inside the overlay directory, the only place the
// provider writes to.
func (r resolver) withTargetPath(d Decision, autoPath string) (Decision, error) {
	target, ok := r.obj.GetAnnotations()[PathAnnotation]
	if !ok {
		if !r.resourceFinder {
			return refuse(d, "%s has no %s annotation and the resource finder is disabled", r.obj.GetName(), PathAnnotation)
		}
		target = autoPath
	}

	overlayDir := r.overlayDir()
	target = path.Clean(target)
	if !strings.HasPrefix(target, overlayDir+"/") {
		return refuse(d, "target path %s of %s is outside the overlay directory %s", target, r.obj.GetName(), overlayDir)
	}
	d.TargetPath = target
	return d, nil
}

func (r resolver) findPatchPath(originalName string) (string, error) {
	b := r.build
	_, kustomization, err := readKustomization(b.fSys, b.dir())
	if err != nil {
		return "", err
	}
	entries, _ := kustomization["patches"].([]any)
	for _, item := range entries {
		entry, _ := item.(map[string]any)
		file, _ := entry["path"].(string)
		// An inline patch has no file to write to.
		if file == "" {
			continue
		}
		filePath := path.Join(b.dir(), file)
		kind, name, err := patchTarget(b, entry, filePath)
		if err != nil {
			return "", err
		}
		if kind == r.obj.GetKind() && name == originalName {
			return strings.TrimPrefix(filePath, "/"), nil
		}
	}
	return r.defaultPath(originalName, ".patch.yaml"), nil
}

// Without a target, a patch entry targets the document its file holds.
func patchTarget(b overlayBuild, entry map[string]any, filePath string) (kind, name string, err error) {
	if target, ok := entry["target"].(map[string]any); ok {
		kind, _ = target["kind"].(string)
		name, _ = target["name"].(string)
		return kind, name, nil
	}

	content, err := b.fSys.ReadFile(filePath)
	if err != nil {
		return "", "", err
	}
	var document struct {
		Kind     string `json:"kind"`
		Metadata struct {
			Name string `json:"name"`
		} `json:"metadata"`
	}
	if err := yaml.Unmarshal(content, &document); err != nil {
		return "", "", fmt.Errorf("parse %s: %w", filePath, err)
	}
	return document.Kind, document.Metadata.Name, nil
}

func (r resolver) overlayDir() string {
	return path.Join(r.build.root, "overlays", r.build.overlay)
}

func (r resolver) defaultPath(originalName, extension string) string {
	return path.Join(r.overlayDir(), strings.ToLower(r.obj.GetKind())+"-"+originalName+extension)
}

func refuse(d Decision, format string, args ...any) (Decision, error) {
	d.Action = ActionRefuse
	d.RefuseMessage = fmt.Sprintf(format, args...)
	return d, nil
}
